DEVICE_CLIENT_KEY_ENV_VAR = "NOVARIS_DEVICE_CLIENT_KEY"
DEVICE_SIGNATURE_SECRET_ENV_VAR = "NOVARIS_DEVICE_SIGNATURE_SECRET"
BEHAVIOURAL_CLIENT_KEY_ENV_VAR = "NOVARIS_BEHAVIOURAL_CLIENT_KEY"
DEVICE_PAYLOAD_VERSION_V1 = "v1"
SECURITY_TIMESTAMP_WINDOW_SECONDS = 300
